apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-db-airflow-redis-0
  namespace: orchestrator
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 150Gi  # Deve ser o mesmo tamanho do PV
