apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv-6
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/airflow-6
  storageClassName: default  # Adicionando a StorageClass
