apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-airflow-postgresql-0
  namespace: orchestrator
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: airflow
    app.kubernetes.io/name: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: default  # ou o nome do seu StorageClass, se diferente
  volumePermissions:
     enabled: true
