apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv-1
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/airflow-1
  storageClassName: default  # Adicionando a StorageClass
