apiVersion: v1
kind: PersistentVolume
metadata:
  name: hive-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /mnt/data/hive-metastore
