apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: gitops
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 32080  # Porta no host que será exposta
  type: NodePort

