apiVersion: v1
kind: Secret
metadata:
  name: kuber-project
  namespace: gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/caiohmb/kuber_project.git
  password: ""
  username: not-used